### ISSUE TITLE
ADRS vignette & template

### ISSUE THREAD

**Issue by jj1994** [pharmaverse/admiralonco#10]
[ADRS Workflow](https://exbpbox.ent.box.com/file/938119687742)

**Comment by rossfarrugia** [comment]
For PD param see https://github.com/pharmaverse/admiral/issues/1063 from admiral core & see ADRS workflow doc for other dependencies on admiral core

**Comment by rossfarrugia** [comment]
Consider ADEVENT possible set-up that some companies use, and include examples where PD and RESP dates are passed from an intermeidate dataset rather than from already derived ADRS params.

**Comment by rossfarrugia** [comment]
See discussion at https://github.com/pharmaverse/admiralonco/issues/25 around setting adsl vars once at the start and then re-using in all further param function calls, as done in ADEX.
