### ISSUE TITLE
Documentation:  derive_param_confirmed_bor - aval_fun argument

### ISSUE THREAD

**Issue by yohannomnes** [pharmaverse/admiralonco#110]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

aval_fun argument is defaulting to aval_resp function which itself maps AVALC values ("CR", "PR", "SD", "NON-CR/NON-PD", "PD", "NE", "MISSING", "ND", othertwise) to exactly the following AVAL values: 1, 2, 3, 4, 5, 6, 7 and NA_real_ and in that exact order. 

I wonder if the vignettes should be more explicit re. guiding companies to define their own function should their own internal mapping differ from the default (the latter being Roche-specific I would imagine).

**Comment by rossfarrugia** [comment]
Thanks @yohannomnes - good feedback! we can address this in the ADRS vignette and maybe add an extra example.

**Comment by yohannomnes** [comment]
Great, thanks!
