### ISSUE TITLE
Documentation:  derive_param_confirmed_bor - reference_date argument

### ISSUE THREAD

**Issue by yohannomnes** [pharmaverse/admiralonco#111]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

reference_date argument mentions: 'Usually it is treatment start date (TRTSDT) or randomization date (RANDDT)'

It could also be the baseline scan date. Is it worth adding?

**Comment by rossfarrugia** [comment]
@yohannomnes if we start listing every eventuality here i thing it would have endless possibility across each company's possible different approaches. i think fine just to leave it as is with listing 2 common examples, but the point made really is that any date could be used here according to your specifications and analysis needs.
