### ISSUE TITLE
Documentation:  derive_vars_duration (in months) for ADTTE

### ISSUE THREAD

**Issue by yohannomnes** [pharmaverse/admiralonco#112]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

If a SAP has a TTE (in months) defined as ((end_date - start_date + 1)*12)/365.25, using the derive_vars_duration function with out_unit = 'months' cannot be used as such.

Alternative is to use out_unit = 'days' and then do the days to months conversion as an extra step.

Has this been raised before?

**Comment by bundfussr** [comment]
@yohannomnes , thanks for raising the issue.
I think you can achieve it by specifying `in_unit = "days"`, `add_one = TRUE`, and `out_unit = "months"`. 

Maybe we should add an example to the ADTTE vignette. @rossfarrugia , what do you think?

**Comment by rossfarrugia** [comment]
Sure, good idea! i will add this example.

**Comment by yohannomnes** [comment]
Thanks both but this is exactly how I was testing it (in_unit = "days", add_one = TRUE, and out_unit = "months") but this gives slightly different results past a certain decimal precision compared to let's stay (in_unit = "days", add_one = TRUE, and out_unit = "days") + (new_var*12)/365.25.

I think this is because of the underlying lubridate::time_length(x, 'months') function that is being used.

**Comment by bundfussr** [comment]
Yes, there are minor differences because `time_length()` takes into account that the length of the months differ. I.e., both `time_length(ymd("2021-01-01") %--% ymd("2021-02-01"), "month")` and `time_length(ymd("2021-02-01") %--% ymd("2021-03-01"), "month")` results in `1`. The differences should occur mainly for short periods.

We could add a `unified` argument to `derive_vars_duration()`. If set to `TRUE`, unified length are assumed for durations in months and years.

However, I am not sure if it is worth the effort. It is unlikely that these minor differences affect the clinical conclusion.

@rossfarrugia , @thomas-neitmann , @bms63 , what do you think?

**Comment by thomas-neitmann** [comment]
This seems to be the same underlying issue as described in https://github.com/pharmaverse/admiral/issues/1358. I've set it on the agenda for next Wednesday's core team meeting.

**Comment by bundfussr** [comment]
I think for `AAGE` the admiral derivation is the correct one. For time-to-event in month both approaches are reasonable. I would tend to use difference in days divided by 30.4375.

**Comment by rossfarrugia** [comment]
Are these just differences down to reporting conventions? If so i'm OK personally with leaving and using the lubridate defaults. There's an expectation from HAs around different conventions between R and SAS default choices like the way rounding is done, and there's a PHUSE WG that raises awareness of this.

**Comment by bundfussr** [comment]
The question is if the time-to-event should be the same for the examples above? Currently you get 1 month for both although its 31 days in the first example and 28 days in the second example.

**Comment by rossfarrugia** [comment]
It's just a different way of looking at the same thing in my mind - technically they both are 1 month and that is more accurate but the way we always did it in the past would have been to calculate in days and then convert assuming each month has equal days. You could argue to leave it and then one option is just to always use days in ADTTE and then convert to months on the TLG side preprocessing if a simple /30.4375 is what is needed.

I'm happy to leave it and I'll add a note to explain in the vignette, as TTE in months is more common in Onco where we often expect(/hope) for longer durations before events.
