### ISSUE TITLE
Documentation:  Add more examples to ADRS vignette

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#115]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

**_Feedback from Roche testers:_**

Check if further examples could be added for Roche standard parameters CBCP, CCB, CRSP, LSTAC.

Explain why some confirmed functions have their own functions and others can re-use existing functions.

_Add RSSEQ to the ordering variables for ASEQ_ (already covered by https://github.com/pharmaverse/admiralonco/issues/79)

Consider same updates for ADRS template.

**Comment by oreillb1** [comment]
Yes that looks good

**Comment by rossfarrugia** [comment]
@oreillb1 FYI I'm adding all except LSTAC as this is covered already by the note in the vignette:

There is flexibility to use `source_pd` argument to only look up to first `PD` assessment, but in the below example all assessments are included.
