### ISSUE TITLE
Documentation:  Link website in About

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiralonco#126]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

You all should link admiralonco website 

![image](https://user-images.githubusercontent.com/10111024/186199123-cfb60c17-0112-43a1-9679-91b08343355a.png)

like how we do it in admiral repo

![image](https://user-images.githubusercontent.com/10111024/186199410-85b48063-792d-43b9-9ea3-0d6f86d3576b.png)

**Comment by rossfarrugia** [comment]
Sure Ben, will do once we release 0.1.0

**Comment by rossfarrugia** [comment]
now added
