### ISSUE TITLE
Research and prototype how inhertParams could be used in admiralonco

### ISSUE THREAD

**Issue by sgorm123** [pharmaverse/admiralonco#129]
### Feature Idea

Splitting out Discussion issue https://github.com/pharmaverse/admiralonco/issues/80

Research and prototype how inhertParams could be used in admiralonco to ensure consistency in argument documentation (See argument file I attach for information).

https://r-pkgs.org/man.html#inheriting-arguments

[Argument_Review.xlsx](https://github.com/pharmaverse/admiralonco/files/9424374/Argument_Review.xlsx)

**Comment by bundfussr** [comment]
The admiralonco functions are superseded by derive_extreme_event(). I would not expect that we develop them further. Thus I am closing this issue.
