### ISSUE TITLE
Ensure consistency in roxygen argument selection, documentation and order in function headers

### ISSUE THREAD

**Issue by sgorm123** [pharmaverse/admiralonco#130]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

Splitting out Discussion issue https://github.com/pharmaverse/admiralonco/issues/80

Ensure consistency in roxygen argument selection, documentation of arguments (e.g. permitted values, required or optional, examples) and order in function headers

Awaiting @thomas-neitmann  draft guidance on the above.

**Comment by thomas-neitmann** [comment]
Sorry for being a bit late.

Some first thoughts:

- No need to add "Required" or "Optional" in parameter documentation. By our programming strategy pptional parameters are those that have `NULL` as default, everything else is required and those parameter that don't have a default value have to be explicitly set by users.
- Only use "Permitted values:" if there is a limited number of strings to choose from (think a CDISC code list), e.g. for the `mode` parameter we often use only `"first"` and `"last"` are valid so these values should be listed along with the default. Don't say something like "Permitted values: data frames".
- The description of every parameter should indicate the expected data type like `data.frame`, `character` or `logical`.

**Comment by bundfussr** [comment]
I would prefer using "Permitted values" for all parameters. Then this information is easier to find. At the moment we are not using "Permitted Values" consistently. I think it would be good to be consistent.

**Comment by sgorm123** [comment]
Thanks @thomas-neitmann.  

Ross @rossfarrugia 
1) **"Required" or "Optional"**: shall I remove these from the bor function?  I like this, but it is not needed in all, so maybe better to be consistent.
2) **Permitted values:** Who makes this decision? I agree with @bundfussr, but defer to others final judgement.

Also, what about the *Default:* argument, I presume this is this only necessary when there is a default set in the function signature, even NULL? I can update this issues as part of: https://github.com/pharmaverse/admiralonco/tree/128_filter_pd_optional_assertions_updated%40devel

Once confirmed.

Thank you all

**Comment by rossfarrugia** [comment]
@sgorm123 
1. yes please remove these
2. i added to core dev team meeting agenda for today to push for a decision and clarity - will also check on your defaults question

**Comment by thomas-neitmann** [comment]
I don't think having a *Default* is particularly useful. You already see that on top in the function signature.

**Comment by sgorm123** [comment]
@rossfarrugia so shall I remove all default text, they are currently in the majority of admiralonco functions?

**Comment by sgorm123** [comment]
One plus side of having defaults is I can see them in the inline help, without having to scroll up to the signature.

![image](https://user-images.githubusercontent.com/31095773/187704010-70d6c4ad-27f9-4411-be05-a3438db3ec35.png)

**Comment by rossfarrugia** [comment]
Summary of discussions at core dev meeting (FYI @sgorm123)
- Defaults: Agreed with Thomas to remove all these for now as its a repeat of info from Usage section and likely might get out of sync/hard to maintain, but a nice to have might be a way to automate this later - as we did see value in not having to scroll up to see this as per Stephen's point
- Permitted values: We agreed these are useful to include for all arguments as it could help bring clarity of expectations to users, but before we add these we should have some controlled terminology to apply (see https://github.com/pharmaverse/admiraldev/issues/64). So don't worry about updating these for admiralonco yet and we can come back to this bit later

Follow-up related issues created for later as FYI:

- https://github.com/pharmaverse/admiral/issues/1401 
- https://github.com/pharmaverse/admiraldev/issues/64
- https://github.com/pharmaverse/admiral/issues/1295
- https://github.com/pharmaverse/admiral/issues/1402

**Comment by sgorm123** [comment]
@rossfarrugia Ive removed all the defaults, updated to make filter_pd optional, and also removed duplicated assertions. 

Im just a little worried about creating a PR until the other items on the devel branch have been accepted, given that there will be conflicts. Should I wait a little to create the PR for issue https://github.com/pharmaverse/admiralonco/issues/128

**Comment by rossfarrugia** [comment]
@sgorm123 yes, as discussed at call please merge https://github.com/pharmaverse/admiralonco/pull/121 first

**Comment by zdz2101** [comment]
Closing to centralize as denoted in https://github.com/pharmaverse/admiraldev/issues/290
