### ISSUE TITLE
derive_param_confirmed_bor function ref_start_window should consider -1 day

### ISSUE THREAD

**Issue by txiao01** [pharmaverse/admiralonco#132]
### What happened?

When using ref_start_window to calculate day ranges, it should be "ADT >= !!reference_date + days(ref_start_window) -1" instead of "ADT >= !!reference_date + days(ref_start_window)", so that the exact day 1 record will be included. 

### Session Information

![Screenshot ](https://user-images.githubusercontent.com/112470029/187388844-75c86d06-9834-4563-aff0-5d3d85f8560f.png)

**Comment by rossfarrugia** [comment]
Discussing offline on email for further context but will close this issue as no update planned.
