### ISSUE TITLE
Bug: Should subject_keys be passed into filter_pd in derive_param_confirmed_resp.R

### ISSUE THREAD

**Issue by sgorm123** [pharmaverse/admiralonco#140]
### What happened?

https://github.com/pharmaverse/admiralonco/blob/devel/R/derive_param_confirmed_resp.R

I think the subject_keys argument in derive_param_confirmed_resp.R should be passed into the filter_pd subject_keys argument , as in all the other function calls.

@bundfussr can you confirm, and I shall make the update as part of this issue , https://github.com/pharmaverse/admiralonco/issues/128, which involves updating all functions (this is how I noticed).

**Comment by bundfussr** [comment]
@sgorm123 , yes, you are right. Good catch!

**Comment by sgorm123** [comment]
@bundfussr great, thanks,  I'll update as part of issue #128
