### ISSUE TITLE
ADTR workflow proposal

### ISSUE THREAD

**Issue by jj1994** [pharmaverse/admiralonco#15]

**Comment by oreillb1** [comment]
Please can ADTR release be expedited, as several studies require this and we would like to test as soon as possible, Thank you.

**Comment by HinalPat** [comment]
Hi All,
Please find 3 documents for review on BOX: https://exbpbox.ent.box.com/folder/154449333406:

- ADTR workflow proposal
- ADTR questions for discussion/ do add more
- ADTR Roche spec - This spec is fairly new in our standards you will see there are some issues noted that will be discussed internally.

Please add comments directly in the word documents.

**Comment by bundfussr** [comment]
@pharmaverse/admiralonco , after adding comments to the word documents please add a short comment here regarding which document you commented on. Box does not generate notifications if the documents are changed or comments added.

**Comment by rossfarrugia** [comment]
@bundfussr can you give a bit more idea on how `derive_vars_merged_summary()` new function would look and what it would provide?

@HinalPat the workflow seems reasonable to me (from my limited knowledge of this ADaM) - look forward to hearing what the others think and whether it's robust for all our co-dev company needs.

**Comment by bundfussr** [comment]
@rossfarrugia , `derive_vars_merged_summary()` should be similar to `derive_summary_records()` except that the summarized values are not added as new observations but as a new variable.

For example, for the derivations of `LSEXP` for the TSD parameter something like the following could be called.
```
derive_vars_merged_summary(
  adtr,
  dataset_add = tu,
  filter_add = TUTESTCD == "TUMIDENT" & TUSTRESC == "TARGET",
  analysis_var = TULNKID,
  summary_fun = function(x) paste(x, collapse = ", "),
  new_var = LSEXP,
  by_vars = vars(USUBJID)
)
```
For each patient it concatenates the tumor ids of the expected target tumors and stores it in the new variable `LSEXP`.

**Comment by amitjaingsk** [comment]
I will also check workflow for ADTR next week..

**Comment by rossfarrugia** [comment]
Thanks @bundfussr! Maybe we can tag this example on to the core dev team discussion Wednesday around https://github.com/pharmaverse/admiral/pull/1484. I'm wondering if at times instead of adding more and more functions would it not be simpler just to have the user use 2 existing functions in conjunction, e.g. I guess the above could be achieved with a call to `derive_summary_records()` then `derive_vars_merged()`. You'll probably point me to many other examples where we already did it this way by creating a new function, but writing that Generic Functions vignette has got me reflecting, and I do worry that the learning curve for adopting admiral is only rising with every new function.

**Comment by bundfussr** [comment]
Technically you could use `derive_summary_records()` (or better `get_summary_records()`) and then `derive_vars_merged()`. But it would be hard to explain why for this derivation two function calls are needed but for others just a single one. And where would we store the information that two calls are needed, in the examples of `derive_vars_merged()` or in the examples of `get_summary_records()`?
I would prefer cleaning up admiral such that we remove overlaps and close gaps.

**Comment by rossfarrugia** [comment]
Fair, let's discuss Wednesday! i was thinking you'd just include these 2 calls in the ADTR template itself. It's a bit like the thinking behind how we do partial date imputations only in one place now and then use these in the functions as a next step. We could do similar with creating whatever you need (flag/summary/most extreme etc) from the additional dataset using one function, and then using one single merge function to add it to the original dataset. But we've probably gone too far now with adding many different variations of the "merged" functions, so your solution is probably cleaner at this stage.

**Comment by amitjaingsk** [comment]
@HinalPat @rossfarrugia @bundfussr I have reviewed the adtr workflow and provided the comments in file on box. Please have a look and we can discuss in out next call.

**Comment by bundfussr** [comment]
@amitjaingsk , thanks. I have added answers on some of your questions. We can discuss further tomorrow.
