### ISSUE TITLE
Display CRAN Date on Changelog Page

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#160]
See https://github.com/pharmaverse/admiraltemplate/issues/34 for details of very minor update needed to _pkgdown.yml.

@HinalPat might be a good one to try out? ;)

**Comment by bundfussr** [comment]
At the moment `news:` is a subitem of `repo:`. Therefore it is ignored and the CRAN dates are displayed. It should be moved to top level.
