### ISSUE TITLE
General Issue: Data Checks

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiralonco#162]
### Background Information

Currently some `derive_param_*()` functions issue a warning if CR->PR occurs in the source data.

- Are the checks at the right place? At the moment the checks are called within the `derive_param_*()` functions. Maybe it is better to call them separately after the creation of the OVR parameters. Then they would fire only once and it would be easier to customize them.

- Do we need more checks, e.g., CR -> SD or PR -> SD?

- The response values to check are hard-coded in the check. Should we make it more flexible?

### Definition of Done

Decision on how data checks should be implemented in admiralonco.

**Comment by HinalPat** [comment]
Agreed to close issue.  Data checks will be part of SDTM checks in pharmaverse.
