### ISSUE TITLE
Minor: tte_source.R should be renamed tte_sources.R for consistency with admiral

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#166]

**Comment by antivistic** [comment]
Hi! I can work on this. Would you also like tte_source_objects.Rd renamed to 
tte_sources_objects.Rd also?

**Comment by rossfarrugia** [comment]
thanks @antivistic - no it's ok you can leave that one as admiral has it as `tte_source_objects.Rd` too - so just the R program name needs updating. 

I couldn't find any other impact of this change, but tagging @bundfussr here in case he could think of any?

**Comment by bundfussr** [comment]
@rossfarrugia , I see no other impact as well.

**Comment by antivistic** [comment]
I put in a pull request for the name change. I am pretty new to this so please let me know if anything else should be done. Thank you!

**Comment by bundfussr** [comment]
Thanks @antivistic .

Could you create a feature branch in admiralonco (not in your fork) as described in https://pharmaverse.github.io/admiraldev/devel/articles/git_usage.html#working-with-feature-branches? Then please create a PR merging the feature branch into `devel` (not `main`). Finally link this issue and the PR via the "Development" section on the right side.
