### ISSUE TITLE
Documentation: Adding Analysis Flag approach for selecting obs up to PD to ADRS vignette

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiralonco#168]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

As an alternative to using `source_pd` the derivation of `ANL02FL` flagging assessments up to PD should be added to the vignette. The admiral function `derive_var_relative_flag()` could be used for this (see https://github.com/pharmaverse/admiral/issues/1453).

**Comment by amitjaingsk** [comment]
@rossfarrugia  This is interesting. I can check with our adam SME but please provide more details on how the ROCHE team is proposing to use CRIT/CRITxxFL flag in this case. The CRIT/CRITxxFL is used for a particular condition which is met by the record( in general) if it is met or not in the BDS structure. So, what should be the proposed value of CRIT/CRITxxFL in our case.?
for eg CRIT1=" OVERALL RESPONSE BEFORE PD" AND CRITxxfl='Y' for before PD record?
we will discuss in the call..

**Comment by rossfarrugia** [comment]
@amitjaingsk we're not actually sure exactly how they propose, they just prefer we find a way using CRITxxFL instead of ANLxxFL but myself and @bundfussr disagree. They're the only folks I've heard concern about using ANLxxFL in this way, and I've seen it done on past filings before with no issue, so we're thinking to push back and keep with our proposed approach. Chat later!

**Comment by amitjaingsk** [comment]
@rossfarrugia @bundfussr @HinalPat I already have derive_var_relative_flag() example call added in the adrs vignette. Do we need to add something further as below or do I miss anything?
### Derive `ANL02FL` {#anl02fl}

```{r, eval=FALSE}
adrs <- adrs %>%
  derive_var_relative_flag(
    by_vars = vars(USUBJID),
    order = vars(ADT, AVISITN),
    new_var = ANL02FL,
    condition = AVALC == "PD",
    mode = "first",
    selection = "before",
    inclusive = TRUE
  )

**Comment by rossfarrugia** [comment]
thanks @amitjaingsk - please tick through all the PR checklist boxes at https://github.com/pharmaverse/admiralonco/pull/174 - i think this change warrants an entry in `NEWS.md`. then me and @bundfussr can re-review and hopefully approve, so we can get merged. i'll look later this week
