### ISSUE TITLE
Add BMS to license for next release

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#173]
Update in LICENSE.md file

**Comment by irgsandy** [comment]
@rossfarrugia , I assigned this task to myself. However, could you let me know what I need to update? Do you want me to put BMS in Line 182 after GSK?

182      Copyright 2021 F. Hoffmann-La Roche AG and GlaxoSmithKline LLC

**Comment by irgsandy** [comment]
I also updated description file with adding BMS into the list. Is it OK?

**Comment by rossfarrugia** [comment]
@irgsandy yes, please could you also add `Amgen Inc.` - we seem to have missed that. 

In the description file you could also add the individuals from BMS who will be contributing too. For now add as contributors, and over time if you develop functions or major components we could change that to authors.
