### ISSUE TITLE
Update vignettes: adrs.Rmd & adtte.Rmd to include the acronym BICR alongside IRF

### ISSUE THREAD

**Issue by HinalPat** [pharmaverse/admiralonco#187]
### Let us know where something needs a refresh or put your idea here!

BICR=Blinded Independent Central Review which is industry used acronym.  
Need to update the documentation in Admiralonco to add '/Blinded Independent Central Review (BICR)' where we say 'Independent Review Facility (IRF)'  -

**Comment by bundfussr** [comment]
@HinalPat , I wonder if we should remove the IRF acronym. It seems to be Roche specific and Roche will change to BICR.

**Comment by HinalPat** [comment]
@bundfussr it appears that its not Roche specific so we will keep both.
