### ISSUE TITLE
New admiralonco function: derive_param_response 

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#20]
### Feature Idea

**derive_param_response:** checks for any CR/PR from OVR (where ANL01FL=”Y”) before first PD as default

Flexibility needed:
- to change the input source parameter from OVR, or the source of PD date
- to change the response criteria searched for (in case need for a different AVALC besides CR/PR to be included as response)

**Details:** checks for any CR/PR (AVALC=”CR” or “PR”) from PARAMCD=”OVR” (where ANL01FL=”Y”) records before first PD as default and sets new parameter record with AVALC=”Y” (AVAL=1) if exists, otherwise sets as AVALC=”N” (AVAL=0). Set ADT as the first date where the condition is fulfilled.
_Note: it is important that ANL01FL=”Y” (or whichever condition is passed below to filter the source records) provides only the eligible records to be considered for this derivation, as explained in the ADRS vignette._

### Relevant Input

```
derive_param_response(
  dataset,
  dataset_adsl,
  filter_source,
  source_pd,
  source_datasets,
  set_values_to,
  subject_keys = vars(STUDYID, USUBJID)
)
```

_Note: explain for the resp_cond argument that this allows user to change the selection of response, e.g. if using iRECIST and needing to use iCR/iPR._

_Note: for source_pd a date_source() object is expected. See https://pharmaverse.github.io/admiral/reference/derive_param_tte.html as an example of how this works._

### Relevant Output

New response parameter: Covers RSP & BCP from ADRS workflow doc (or CBCP for confirmed responses feeding in CBOR for example).

### Reproducible Example/Pseudo Code

```
pd <- date_source(
  dataset_name = “adrs”,
  date = ADT,
  filter = PARAMCD == “PD” & AVALC == “Y”
)

derive_param_response(
  dataset = adrs,
  dataset_adsl = adsl,
  filter_source = PARAMCD == "OVR" & AVALC %in% c(“CR”, “PR”) & ANL01FL == "Y",
  source_pd = pd,
  source_datasets = list(adrs = adrs),
  set_values_to = vars(
	PARAMCD = "RSP",
	PARAM = " Response by Investigator (confirmation not required)",
	PARCAT1 = "Tumor Response",
	PARCAT2 = "Investigator",
	PARCAT3 = "Recist 1.1",
	ANL01FL = "Y")
)
```

**Comment by rossfarrugia** [comment]
Reminder to use filter_pd from #18 once available

**Comment by bundfussr** [comment]
@kabis-ops , I replaced `source_param` with `filter_source`. I.e., instead of specifying the parameter code of the source parameter an arbitrary condition for selecting the source records can be specified. This allows to use other variables than `ANL01FL`.

**Comment by kabis-ops** [comment]
Hi @bundfussr , @rossfarrugia , May I ask 
1) if we really need to specify both `filter_source` and `  resp_cond` parameter?
(I think we already discussed it but i cannot remind the rational for these 2 param: )
``` 
filter_source = PARAMCD == "OVR" & ANL01FL == "Y",
resp_cond = AVALC %in% c(“CR”, “PR”) & ANL01FL=”Y”
```

Can't we include the `resp_cond` into the `filter_source` param, i.e. : `filter_source = PARAMCD == "OVR" & AVALC %in% c(“CR”, “PR”) & ANL01FL == "Y"` ?

2) Should we rename the parameter `source_pd` into something like `source_end_date`? I believe we should be able to derive the first response before the first PD or the first anti-cancer therapy or any other evenT?

3) For subject without a response, the function would return a record with AVALC = N and ADT would be NULL, right?

**Comment by rossfarrugia** [comment]
@kabis-ops - good questions. here's some replies from my perspective:
1. i agree - you're right. would be cleaner with just `filter_source`. i think this was a remnant of the fact we started with `source_param` here but `filter_source` now covers the one place you can do both where clauses.
2. i would leave this one as it is as any end window filtering can be achieved in ANL01FL as explained in the ADRS vignette so far (see latest draft at https://github.com/pharmaverse/admiralonco/blob/10_adrs_vignette_template/vignettes/adrs.Rmd - see "Pre-processing of Input Records" section).
3. agree - that's how the Roche specs have it.

**Comment by kabis-ops** [comment]
Hi @rossfarrugia , Thanks.
Regarding 2) I am still not convinced. 🙄 
We can definitively create another ANL0xFL and use it in `filter_source` but can't we also achieve this with the  `source_pd` param?
```
nact<- date_source(
  dataset_name = “adevent”,
  date = ADT,
  filter = PARAMCD == “NACT” & AVALC == “Y”
)
derive_param_response(
  dataset = adrs,
  dataset_adsl = adsl,
  filter_source = PARAMCD == "OVR" & AVALC %in% c(“CR”, “PR”) & ANL01FL == "Y",
  source_pd = list(nact),
  source_datasets = list(adrs = adrs, adevent=adevent),
  set_values_to = vars(
	PARAMCD = "RSP1",
	PARAM = " Response by Investigator (confirmation not required)  before the start of a new therapy")
)
```

Also, @bundfussr , I guess we will have only one element in `source_pd`, so just wondering if we need to specify it as a list?
Could we have `source_pd = pd` instead of `source_pd= list(pd)`?

**Comment by rossfarrugia** [comment]
@kabis-ops absolutely - the approach is flexible to be used either way by our users, but our admiral recommended way in the vignette and template would be to use ANLxxFL for all filtering of records needed for downstream derivations as it might not just be censoring at an end date - you could also cover things like only records after treatment start/randomization date here or filtering out invalid records etc. It gives far more power to the users this way than just an end date. The reason we didn't also cover PD in this way via ANLxxFL was because you can't really call an endpoint BOR for example unless you enforce the PD censor rules. This was discussed a lot as part of the ADRS workflow discussions and review and it seemed the easiest way to get consensus across the 3 companies and give users plenty of flexibility for their company-specific implementations, so i'm confident it should work.

good question about the need for list. @bundfussr that's simialr to our other discussion about `source_dataset` for Teckla's function. it's always a question of ease for the users to consistently know to always use list here vs remembering for this argument there can only ever be one PD source. happy to go with Stefan's call here!

**Comment by kabis-ops** [comment]
Hi @bundfussr , @rossfarrugia 
some additional questions/comments:
- i have added a `subject_keys` parameters: since we create the records from `datasets_adsl`, we need a key to merge with `dataset` or the source_datasets. Ok with you? This should apply to other functions too. Please tag the other  dev if you agree.
- In the Roche spec, we select responses before **or on** the first PD. Do we want to add flexibility here to allow to select responses strictly before PD? I know this is unlikely we can get a CR/PR the same day as a PD, just asking if we need to think about that ?
- it seems `filter_if` from admiral is not exported as i need to specify admiral:::filter_if? I will raise an issue in admiral core if this is confirmed

**Comment by bundfussr** [comment]
Hi @kabis-ops ,

- yes, we should add the `subject_keys` parameter to all functions which merge by subject.
- I think at the moment we do not need an option for selecting observations strictly before PD. If there is more than one assessment per day, the assessment to use should be derived before deriving the parameters, e.g., by deriving `ANL01FL` like in the Roche specs.
- `filter_if` is exported. Do you get something like
    ```
    Error in .p(column, ...) : object 'USUBJID' not found
    ```
    ?
    You get this if `admiral` is not loaded but `dplyr` is loaded (there is a `filter_if()` function in `dplyr`).

**Comment by rossfarrugia** [comment]
for bullet 2 agree let's not over-complicate it for now and see what comes back with user feedback - just make clear in the function documentation details section that this is what is being done here. does seem odd that we don't use strictly before here, but i guess it's because having a PR and PD on same day is implausible as you say.

**Comment by kabis-ops** [comment]
Hi @bundfussr , @rossfarrugia 
I think this will be my last question:
A patient may have multiples CR/PR before PD, and we need to select the first one, so we need a date.
Do we expect the input datasets to contains `ADT`? or should we adjust the function so that it is similar to `admiral::derive_param_first_event` where a `date_var` is specified to identify the first obs and populate the date variable for the additional records? If so, I will make use of the function in the `derive_param_response`, unless you disagree.
Thank you

**Comment by bundfussr** [comment]
At the moment we have hard-coded `ADT` in the admiralonco functions. So I would assume that `ADT` is in the input dataset of `derive_param_response()` and set `date_var = ADT` in the call of `derive_param_first_event()`.

We can discuss after the first admiralonco release if we need more flexibility at this point.
