### ISSUE TITLE
Documentation: Enable validation report generation for this repository

### ISSUE THREAD

**Issue by cicdguy** [pharmaverse/admiralonco#202]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

Need to add https://github.com/pharmaverse/admiral/blob/main/.github/workflows/common.yml#L27-L30 and https://github.com/pharmaverse/admiral/blob/main/.github/workflows/common.yml#L57-L62 to the `check.y[a]ml` workflow.

**Comment by dgrassellyb** [comment]
already exists - no action needed
