### ISSUE TITLE
filter_confirmation() was deprecated in admiral 

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#205]
### What happened?

R CMD Check:
Error: Error: processing vignette 'adrs.Rmd' failed with diagnostics:
`filter_confirmation()` was deprecated in admiral 0.10.0 and is now
defunct.
ℹ Please use `filter_joined()` instead.

Impacts: check_crpr.R, derive_param_confirmed_resp.R, and derive_param_confirmed_bor.R, and update the imports list in admiralonco-package.R

**Comment by bundfussr** [comment]
This is fixed in https://github.com/pharmaverse/admiralonco/pull/194.

**Comment by rossfarrugia** [comment]
Thanks Stefan!
