### ISSUE TITLE
New admiralonco function: derive_param_clinbenefit

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#21]
### Feature Idea

**derive_param_clinbenefit:** checks for RSP record with AVALC=”Y” or a sustained period of time before PD record with AVALC=”Y” as default

Flexibility needed:
- to change the input source parameter from OVR, or source of response (e.g. you might want to feed in a different parameter such as CRSP for confirmed responses only), or the source of PD date
- reference date from ADSL to use and <yy> days after that would count as “sustained period of time”

**Details:** checks for response (PARAMCD=”RSP” with AVALC=”Y”) or a sustained period of time before PD record with AVALC=”Y” as default and sets new parameter record with AVALC=”Y” (AVAL=1) if exists, otherwise sets as AVALC=”N” (AVAL=0). Set ADT as the first date where the condition is fulfilled.
To check for sustained period of time before PD, subject would need to have a valid non-PD assessment at least xxx days after ADSL reference date (e.g. not NE or NA or missing).
_Note: it is important that ANL01FL=”Y” provides only the eligible records to be considered for this derivation, as explained in the ADRS vignette._

Question for GSK/Amgen: any more "non-valid" response assessment values you ever see?

### Relevant Input

```
derive_param_clinbenefit(
  dataset,
  dataset_adsl,
  filter_source,
  source_resp,
  source_pd,
  source_datasets,
  reference_date,
  ref_start_window,
  set_values_to,
  subject_keys = vars(STUDYID, USUBJID)
)
```
_Note: for source_pd or source_resp a date_source() object is expected. See https://pharmaverse.github.io/admiral/reference/derive_param_tte.html as an example of how this works._

### Relevant Output

New parameter: Covers CB (or CCB for confirmed responses) from ADRS workflow doc.

### Reproducible Example/Pseudo Code

```
pd <- date_source(
  dataset_name = “ADRS”,
  date = ADT,
  filter = PARAMCD == “PD” & AVALC == “Y”
)

resp <- date_source(
  dataset_name = “ADRS”,
  date = ADT,
  filter = PARAMCD == “RSP” & AVALC == “Y”
)

derive_param_clinbenefit(
  dataset = adrs,
  dataset_adsl = adsl,
  filter_source = PARAMCD == "OVR" & ANL01FL == "Y",
  source_resp = list(rsp),
  source_pd = list(pd),
  source_datasets = list(adrs = adrs),
  reference_date = TRTSDTM,
  ref_start_window = 28,
  set_values_to = vars(
	PARAMCD = "CB",
	PARAM = " Clinical Benefit by Investigator (confirmation for response not required)",
	PARCAT1 = "Tumor Response",
	PARCAT2 = "Investigator",
	PARCAT3 = "Recist 1.1",
	ANL01FL = "Y")
)
```

**Comment by rossfarrugia** [comment]
As per discussion at team call yesterday, reminder to include ND as an invalid assessment in above derivation.

**Comment by rossfarrugia** [comment]
Reminder to use filter_pd from https://github.com/pharmaverse/admiralonco/issues/18 once available

**Comment by bundfussr** [comment]
@amsmith214 , I replaced `source_param` with `filter_source`. I.e., instead of specifying the parameter code of the source parameter an arbitrary condition for selecting the source records can be specified. This allows to use other variables than `ANL01FL`.

**Comment by amsmith214** [comment]
i know this is partially my fault for being out on study work for so long, but i do not really understand the `source_datasets` parameter. it seems like based on the proposed workflow, it will be trivially specified as list(adrs = adrs) almost all the time. is there a reason not to do `eval(parse_expr(source_pd$dataset_name))` and save a parameter?

**Comment by rossfarrugia** [comment]
Adding reply from Stefan via Slack for completeness in case anyone ever looks back at this question:

We introduced this approach because it allows to define the `date_source` object independent of the data. For example you could define
```
first_pd <- date_source(
  dataset_name = "adrs",
  filter = PARAMCD == "PD",
  date = ADT
)
```
at company level. The dataset name ("adrs") is linked to the actual dataset at study level via the `source_datasets` parameter. In many cases the dataset may have the same name but not always. E.g., many programmers like to number the intermediate datasets. So their dataset may be named adrs3 and they would specify `source_datasets = list(adrs = adrs3)`. In this case `eval(parse_expr(source_pd$dataset_name))` would not work.
