### ISSUE TITLE
New admiralonco function: derive_param_bor

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#22]
### Feature Idea

derive_param_bor: checks for best overall response from OVR (where ANL01FL=”Y”) up to/including first PD as default

Flexibility needed:
- to change the input source parameter from OVR, or the source of PD date
- to change the ADSL reference date (e.g. TRTSDT/RANDDT) and the xxx days after this time to allow an SD or NON-CR/NON-PD to count from

**Details:** checks for best overall response from PARAMCD=”OVR” (where ANL01FL=”Y”) up to/including first PD as default and sets new parameter record with AVAL/AVALC from the source record. Set ADT as the first date where the condition is fulfilled. 
BOR is set to 'NE', in the case where the subject has only AVALC = 'SD' or 'NON-CR/NON-PD' less than xxx days after the reference date from ADSL.
_Note: it is important that ANL01FL=”Y” provides only the eligible records to be considered for this derivation, as explained in the ADRS vignette._ 

### Relevant Input

```
derive_param_bor(
  dataset,
  dataset_adsl,
  filter_source,
  source_pd,
  source_datasets,
  reference_date,
  ref_start_window,
  set_values_to,
  subject_keys = vars(STUDYID, USUBJID)
)
```
_Note: for source_pd a date_source() object is expected. See https://pharmaverse.github.io/admiral/reference/derive_param_tte.html as an example of how this works._

### Relevant Output

New parameter: Covers BOR from ADRS workflow doc.

### Reproducible Example/Pseudo Code

```
pd <- date_source(
  dataset_name = “adrs”,
  date = ADT,
  filter = PARAMCD == “PD” & AVALC == “Y”
)

derive_param_bor(
  dataset = adrs,
  dataset_adsl = adsl,
  filter_source = PARAMCD == "OVR" & ANL01FL == "Y",
  source_pd = list(pd),
  source_datasets = list(adrs = adrs),
  reference_date = TRTSDT,
  ref_start_window = 28,
  set_values_to = vars(
	PARAMCD = "BOR",
	PARAM = " Best Overall Response by Investigator (confirmation not required)",
	PARCAT1 = "Tumor Response",
	PARCAT2 = "Investigator",
	PARCAT3 = "Recist 1.1",
	ANL01FL = "Y")
)
```

**Comment by rossfarrugia** [comment]
Reminder to use filter_pd from https://github.com/pharmaverse/admiralonco/issues/18 once available

**Comment by sgorm123** [comment]
@rossfarrugia What is the timeline for this one? I can pick this one up next, but probably need a week or so with my Amgen commitments.

**Comment by rossfarrugia** [comment]
@sgorm123 that would work, as i would even recommend waiting on @bundfussr to finish https://github.com/pharmaverse/admiralonco/issues/24 first and then your code would be a streamlined version of this without the confirmation bits.

**Comment by bundfussr** [comment]
@sgorm123 , I have pushed a draft of `derive_param_confirmed_bor()` to the `24_derive_param_confirmed_bor` branch. I think you can almost use the same code for `derive_param_bor()`. Just the conditions for CR and PR are much simpler.

**Comment by rossfarrugia** [comment]
@sgorm123 i assigned you here and then @mattmarino could take on https://github.com/pharmaverse/admiralonco/issues/31 to get some experience of admiral development.

**Comment by mattmarino** [comment]
@rossfarrugia Thanks!! I'm very busy the next couple days, so I hope to start working on this the beginning of next week.

**Comment by sgorm123** [comment]
@rossfarrugia @bundfussr **_Wrt BOR is set to 'NE', in the case where the subject has only AVALC = 'SD' or 'NON-CR/NON-PD' less than xxx days after the reference date from ADSL._** 
So the column name passed into the argument reference_date  specifies this column from ADSL to use, correct? 
I do not assume this column is in the dataframe passed into the dataset argument.

I ask, as this is different to derive_param_confirmed_bor which uses reference_dat(with an asserts to make sure it is there) from the dataset argument.

**Comment by bundfussr** [comment]
@sgorm123 , you should expect that `reference_date` is in `dataset` because in the second step of the ADRS workflow we merge all ADSL variables required for the parameter to ADRS.

**Comment by sgorm123** [comment]
Ah yes, sorry for the miss, and thanks.
