### ISSUE TITLE
New admiralonco function: derive_param_confirmed_resp 

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#23]
### Feature Idea

derive_param_confirmed_resp: checks for any confirmed CR/PR from OVR (where ANL01FL=”Y”) as default

Flexibility needed:
- to change the input source parameter from OVR (e.g. to use BOR or IRF instead of investigator), or the source of PD date
- to change the response criteria searched for (in case need for a different AVALC besides CR/PR to be included as response)
- greater than or equals yy days apart check for confirming the response

**Details:** checks for any confirmed CR/PR (AVALC=”CR” or “PR”) from PARAMCD=”OVR” (where ANL01FL=”Y”) records before first PD as default and sets new parameter record with AVALC=”Y” (AVAL=1) if exists, otherwise sets as AVALC=”N” (AVAL=0). Set ADT as the first date where the condition is fulfilled.
_Note: it is important that ANL01FL=”Y” (or whichever condition is passed below to filter the source records) provides only the eligible records to be considered for this derivation, as explained in the ADRS vignette._ 

### Relevant Input

```
derive_param_confirmed_resp(
  dataset,
  dataset_adsl,
  filter_source,
  source_pd,
  source_datasets,
  ref_confirm,
  max_nr_ne,
  accept_sd,
  set_values_to,
  subject_keys = vars(STUDYID, USUBJID)
)
```
_Note: for source_pd a date_source() object is expected. See https://pharmaverse.github.io/admiral/reference/derive_param_tte.html as an example of how this works._

_Note: explain for the resp_cond argument that this allows user to change the selection of response, e.g. if using iRECIST and needing to use iCR/iPR._

### Relevant Output

New parameter: Covers CRSP from ADRS workflow doc.

### Reproducible Example/Pseudo Code

```
pd <- date_source(
  dataset_name = “adrs”,
  date = ADT,
  filter = PARAMCD == “PD” & AVALC == “Y”
)

derive_param_confirmed_resp(
  dataset = adrs,
  dataset_adsl = adsl,
  filter_source = PARAMCD == "OVR" & ANL01FL == "Y",
  source_pd = list(pd),
  source_datasets = list(adrs = adrs),
  resp_cond = AVALC %in% c(“CR”, “PR”) & ANL01FL=”Y”,
  ref_confirm = 28,
  max_nr_ne = 1,
  accept_sd = FALSE,
  set_values_to = vars(
	PARAMCD = "CRSP",
	PARAM = " Confirmed Response by Investigator",
	PARCAT1 = "Tumor Response",
	PARCAT2 = "Investigator",
	PARCAT3 = "Recist 1.1",
	ANL01FL = "Y")
)
```

**Comment by rossfarrugia** [comment]
Wait for https://github.com/pharmaverse/admiralonco/issues/19 before starting

**Comment by rossfarrugia** [comment]
Reminder to use filter_pd from https://github.com/pharmaverse/admiralonco/issues/18 once available

**Comment by bundfussr** [comment]
The workflow is the same as for https://github.com/pharmaverse/admiralonco/issues/24.

**Comment by bundfussr** [comment]
I shortened the name to `derive_param_confirmed_resp()` because lintr complained that it should not be longer than 30 characters.
