### ISSUE TITLE
General Issue: Website multi-versions

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#242]
### Background Information

See admiral website, we should offer something more like the below where you can navigate to past releases:

![image](https://github.com/pharmaverse/admiralonco/assets/82581364/83db4ea3-b1d0-4be7-afc3-19cacaeb3deb)

This will become even more important with the upcoming admiralonco releases given you're going for such a refactor to enable new indications. I know of a filing for example that will use this current admiralonco version so FDA etc might look to the documentation and need to see the exact version as used in the code submissions, or else it could be confusing. 

FYI @bundfussr @amit

### Definition of Done

Same approach to versions navigation on website as admiral uses

**Comment by bundfussr** [comment]
@rossfarrugia , there is no pull request to review but maybe you want to have a look before we close the issue. See https://pharmaverse.github.io/admiralonco/main/ for the website including the old versions.

**Comment by rossfarrugia** [comment]
This is great - thanks @bundfussr! happy to close the issue
