### ISSUE TITLE
Feature Request:  Complete GitHub repo

### ISSUE THREAD

**Issue by kabis-ops** [pharmaverse/admiralonco#27]
### Feature Idea

- add required folders to the gitHub repo:

- [x]   R/, 
- [x]   Vignettes/, 
- [x]   data/ , 
- [x]   inst/templates, 
- [x]  test/testthat...

  
 - add other files:

- [x]    renv.lock , 
- [x]    NAMESPACE, 
- [x]    add lintr

   
@bundfussr @thomas-neitmann : any additional folders/files needs to be added?

**Comment by bundfussr** [comment]
As far as I remember, you can not add empty folders to git.

**Comment by amsmith214** [comment]
i suspect i'd be called hacky but you can create a blank text file called ".gitkeep" (or whatever) and place that in a new folder, then delete the text file, i think.

**Comment by rossfarrugia** [comment]
see slack chat - may be worth adding a NEWS.md with one bullet for 0.1.0 release

**Comment by rossfarrugia** [comment]
As part of this issue will also Include ". Run `styler::style_file()` to style R and Rmd files" in PR template - thanks for the suggestion @sgorm123!
