### ISSUE TITLE
devel branch still exists in this repo

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#282]
@bundfussr should this be removed? as could cause confusion and people might accidentally branch from/merge to `devel `instead of `main`.

**Comment by bundfussr** [comment]
Yes, we can remove it.

**Comment by rossfarrugia** [comment]
thanks - appreciate if you can make the updates for next release. you'll have to align the branch protection rules now with admiral core

**Comment by bundfussr** [comment]
`README.md` needs to be updated.

**Comment by bundfussr** [comment]
I have removed all out of date branches as well.
