### ISSUE TITLE
Feature Request:  Implement `filter_confirmation()`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiralonco#30]
### Feature Idea

Implement
```
filter_confirmation(
  dataset,
  by_vars,
  join_vars,
  first_cond = NULL,
  order,
  filter
)
```

#### Parameter

- `dataset`: Input dataset
- `by_vars`: by variables, the variables are used as by variables for joining the input dataset with itself.
- `join_vars`: the specified variables are joined to the input dataset, the suffic ".join" is added to their names. These variables can be used in the conditions specified for `first_cond` and `filter`.
- `first_cond`: condition for selecting the confirmation visit, e.g., `AVALC.join == "CR" & ADT.join >= ADT + days(ref_confirm)`
- `order`: variables determining the order of the assessments, e.g., `vars(ADT)` or `vars(ADTM, ASEQ)`
- `filter`: condition for selecting the observations to keep. Summary functions like `all()` can be used. For each assessment in the input dataset they summarize the data from the assessment to the confirmation assessment defined by `first_cond`.

#### Workflow

1. create unique observation number (`derive_var_obs_nr(dataset_ovr, new_var = temp_obs_nr)`)
2. join dataset with itself by subject (`left_join(dataset_ovr, select(dataset_ovr, AVALC, ADT), by = USUBJID, suffix = c("", ".join"))`)
3. select observations up to first possible confirming event (defined by `first_cond`), e.g., `AVALC.join == "CR" & ADT.join >= ADT + days(ref_confirm)`
For this we could implement `filter_relative` as suggested in https://github.com/pharmaverse/admiral/issues/1023.
5. select groups (defined by `temp_obs_nr`) which fulfill confirmation criteria (defined by `filter`), e.g., `all(AVALC.join %in% c("CR", "NE")) & count_vals(var = AVALC, val = "NE") <= 1`
    where `count_vals()` is another helper function defined as
    ```
    count_vals <- function(var, val){
      length(var[var == val])
    }
    ```
6. reduce selected observations to one per `temp_obs_nr` (`filter_extreme()`) and drop `AVALC.join` and `ADT.join` (`select()`).

### Reproducible Example/Pseudo Code

```
filter_confirmation(
  adrs_ovr,
  by_vars = vars(USUBJID),
  join_vars = vars(AVALC, ADT),
  first_cond = AVALC.join == "CR" & ADT.join >= ADT + days(28),
  order = vars(ADT),
  filter = all(AVALC.join %in% c("CR", "NE")) & count_vals(var = AVALC, val = "NE") <= 1
)
```
select all observations from `adrs_ovr` where `AVALC == "CR"` and there is a second CR observation at least 28 thereafter and with at most one NE observation and arbitrary CR observations in between.

**Comment by bundfussr** [comment]
@rossfarrugia , I have created the issue in admiralonco due to your comment in https://github.com/pharmaverse/admiralonco/issues/18. If I should move it to admiral core, please let me know.

Maybe we could use the function for the COVID flags in admiralroche.

**Comment by rossfarrugia** [comment]
@bundfussr instead of making this one generic i would focus on making it what we need for admiralonco to confirm responses only. i'm sure there are going to be parts of this rule where flexibilities are required specific to response confirmation, and as it's one of the most complex pieces of ADRS i'm happy for it to have it's own dedicated clear function and documentation page. there will be other times i'm sure where we need to compare 2 records from same dataset to check some condition, but i think for me this one warrants being it's own dedicated function `filter_confirmation` - like we've done with the other new admiralonco functions for BOR etc.

for each required flexibility you could then consider how best to achieve them for this specific need, e.g. instead of using count_vals to count NEs included within the filter call (which is quite difficult to follow and easy to miss), maybe we could have a dedicated argument such as # of NEs permitted in between, and the user could enter 0, 1, 2, etc.

what do you think? if you agree please edit the above with another proposal and happy to review, although please include plain english descriptions for the arguments, as i wasn't in the call to discuss response confirmation, so i might be slower to pick up what flexibilities other companies need.

**Comment by bundfussr** [comment]
@rossfarrugia , I designed the function to cover the three cases we need for admiralonco ("CR" in `derive_param_confirmed_bor()`, "PR" in `derive_param_confirmed_bor()`, and "Y" in `derive_param_confirmed_response()`). That it could be used for the COVID flags in admiralroche is just a side-effect.

My idea was that we build the conditions for selecting the confirmed response in `derive_param_confrimed_bor()` and `derive_param_confirmed_response()` and pass them to `filter_joined()`. The conditions would be based on the parameters `ref_confirm`, `max_nr_ne`, `max_nr_sd` and would include the hard-coded parts like CR can be confirmed by CR only, PR can be confirmed by CR or PR.

As I understand your idea you want to move this step into `filter_confirmation()`. So `filter_confirmation()` would provide `ref_confirm`, `max_nr_ne`, and `max_nr_sd` parameters.
The crucial question is: How would you pass the hard-coded parts to `filter_confirmation()`? I.e., how does the function know if CR for confirmed BOR should be selected or Y for confirmed response?

We could add a `target` parameter to `filter_confirmation()`, which could be set to keywords like `"BOR_CR"`, `"BOR_PR"`, and `"RESPONSE_Y"`.

However, I do not see the benefit.
- More code is required because we need an additional `if` `else` chain to handle the `target` parameter.
- The code is less readable because the interesting information (the conditions) is moved to a lower level (from `derive_param_confirmed_*()` to `filter_confirmation()`).
- More documentation is required because we need to document the construction of the conditions for both `derive_param_confirmed_*()` and `filter_confirmation()`.
- `filter_confirmation()` can be used only for the three use cases we are implementing at the moment.

What do you think?

**Comment by bundfussr** [comment]
@rossfarrugia , I have updated the description of the issue to describe the parameters and point out where they are used in the workflow.

**Comment by rossfarrugia** [comment]
ok @bundfussr go for it with your design, i just ask to use `filter_confirmation` naming as i find `filter_joined` too generic and confusing to understand, especially as this helper function will live in admiralonco not admiral core. i'm guessing the BOR function for example then will run this helper function multiple times given what can confirm a CR is different to what can confirm a PR for example.
