### ISSUE TITLE
Create example `tte_source` objects for oncology TTE endpoints

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#31]
### Feature Idea

Object to share some common examples of TTE source objects as in Step 2 table of the ADTTE workflow: https://exbpbox.ent.box.com/file/945202142113. 

See {admiral} example at https://github.com/pharmaverse/admiral/blob/main/R/tte_sources.R

### Relevant Input

N/A

### Relevant Output

Pre-defined `tte_source` objects for Onco that can be used as input to `derive_param_tte()` in the ADTTE template

### Reproducible Example/Pseudo Code

```
death_event <- event_source(
  dataset_name = "adrs",
  filter = PARAMCD == “DEATH” & AVALC == “Y” & ANL01FL == “Y",
  date = ADT,
  set_values_to = vars(
    EVNTDESC = "Death",
    SRCDOM = "ADRS",
    SRCVAR = "ADT"
  )
)
```

**Comment by rossfarrugia** [comment]
@mattmarino as discussed yesterday i think this would be an ideal first issue to pick up and fine to complete this sometime over the next week or 2 around your other commitments.

**Comment by sgorm123** [comment]
@rossfarrugia, shall I leave this one then Ross? I have not started.

**Comment by rossfarrugia** [comment]
@sgorm123 yes please - pick up the BOR one instead when you get chance. and this one should be a good option for Matt as he was looking for an issue to start with yesterday.

**Comment by mattmarino** [comment]
@rossfarrugia I'm running into an issue in admiralonco of: **could not find function "event_source"** -- seems to work fine in regular admiral. Am I missing something here?

**Comment by rossfarrugia** [comment]
@mattmarino was hard to find your code as you have 2 branches with 31 prefix, maybe delete the one you're not using? Also when you commit if you include #<issue_number> in the commit message it gets linked with the issue. I found it here though https://github.com/pharmaverse/admiralonco/commit/a1d2bbc948a0233b72268d180106b4d764b8bed9

try adding `importFrom(admiral,event_source)` to the NAMESPACE file. i tag @bundfussr just in case i miss any other required steps here.

**Comment by bundfussr** [comment]
@mattmarino , you need to import the `event_source()` function as @rossfarrugia pointed out. But please do not edit the `NAMESPACE` file. This is a generated file (generated by calling `devtools::document()`). Please add `event_source` to the `@importFrom` tag in `admiralonco-package.R` and then call `devtools::document()`.
If you add anything to `admiralonco-package.R` please add it such that the functions are ordered alphabetically. Then it is easier to maintain this file.

**Comment by bundfussr** [comment]
Yes, after updating `admiralonco-package.R` and calling `devtools::document()` you should see `importFrom(admiral,event_source)` in `NAMESPACE`.

**Comment by rossfarrugia** [comment]
@mattmarino note that we removed the "onco_" from this helper object now - it wasn't needed

**Comment by mattmarino** [comment]
@rossfarrugia Thanks, I have updated to the new name. I have started a draft pull request and added you as a reviewer
