### ISSUE TITLE
R CMD checks set-up

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#36]
### Feature Idea

Copy over any relevant auto-checks from https://github.com/pharmaverse/admiral/tree/main/.github/workflows and then edit the branch protection rules to require status checks before merging to `devel` and `main` like in admiral example below:

![image](https://user-images.githubusercontent.com/82581364/171118899-847ace8b-393b-4908-9104-1685631f4268.png)

### Relevant Input

N/A

### Relevant Output

N/A

### Reproducible Example/Pseudo Code

N/A

**Comment by rossfarrugia** [comment]
@thomas-neitmann after you're done with admiral release to CRAN would you be able to help us with this one for admiralonco please?

**Comment by rossfarrugia** [comment]
Actually sorry i just saw https://github.com/pharmaverse/admiralonco/pull/32 from @dinakar29 - do we have to wait until that is merged to main to be able to change the branch protection rules to add the required status checks?

**Comment by dinakar29** [comment]
> Actually sorry i just saw #32 from @dinakar29 - do we have to wait until that is merged to main to be able to change the branch protection rules to add the required status checks?

You could actually turn on status checks via branch protection for `main` even before the workflows are merged back into it. When you create the PR to merge into main, it'll verify the checks and assert status checks are passing.

**Comment by rossfarrugia** [comment]
we both have admin access @bundfussr so we can always override these in the meantime if we ever need to.

**Comment by dinakar29** [comment]
Yes, the 

> I think we can not copy all workflows from admiral because the R-CMD checks should be slightly different. For PRs into `devel` the development version of admiral should be used. The CRAN version of admiral should be used for PRs into `main` only.
> 
> I think we should fix this first before we set the R-CMD checks to required.

Yes, this is pending. This is something that we can easily do with [the staged.deps action](https://github.com/marketplace/actions/staged-dependencies-action)
