### ISSUE TITLE
Explore how we can make list/use_ad_template work for our onco templates

### ISSUE THREAD

**Issue by jj1994** [pharmaverse/admiralonco#41]
Check out [here]( https://pharmaverse.github.io/admiral/articles/admiral.html#starting-a-script) for more information

**Comment by rossfarrugia** [comment]
@thomas-neitmann we'd appreciate any ideas you have here. would we need an onco version of these or any clever way to be able to check templates across any of the admiral family of packages that you've loaded?

**Comment by thomas-neitmann** [comment]
@rossfarrugia See my ideas on this issue in https://github.com/pharmaverse/admiral/issues/1205.

**Comment by rossfarrugia** [comment]
thanks @thomas-neitmann will close the issue here then. appreciate if we could have the update available by end of this month, as that's when the testers will start to look at onco and they'll want an easy way to try out our ADRS and ADTTE templates.
