### ISSUE TITLE
Potential New Categories of Response

### ISSUE THREAD

**Issue by sgorm123** [pharmaverse/admiralonco#45]
`derive_param_bor` and `derive_param_confirmed_bor` (and maybe others) may need to be updated to handle additional response values above the default set: `c("CR", "PR", "SD" , "NON-CR/NON-PD", "PD", "NE", "ND"). `

I have seen examples in testing of UNDEFINED, there may be more once testing begins, so we need to address this at some point.

**Comment by rossfarrugia** [comment]
@amitjaingsk also raised: some vendors also use 'NA' instead of ND ( no disease)

**Comment by sgorm123** [comment]
@rossfarrugia @amitjaingsk This issue is pertinent to todays discussion. Maybe we do need a mechanism to convert AVALC into a numeric sort for determining best response.

**Comment by rossfarrugia** [comment]
@sgorm123 discussed briefly this point with @bundfussr before and the feeling is things like BOR are likely going to need different functions for new response criteria beyond RECIST (where new response values like iCR etc get considered) as trying to make a single function to cover all could end up unimaginably complex to maintain and test. I do feel though improvements like being discussed at https://github.com/pharmaverse/admiralonco/issues/85 could definitely make the simpler functions more robust to work across different response criteria/onco indications.

**Comment by bundfussr** [comment]
@rossfarrugia , I would keep the question how we implement different response criteria beyond RECIST 1.1 open. When I got two example specs for other response criteria I was quite surprised by the variety of response values. Unfortunately, the specs did not include any confirmed endpoints. I would like to have a better overview of the different response criteria and try to find out what is common across them and what is different. I think without that it is hard to decide on a good approach.

I am concerned that if we decide now to implement new functions for each response criterion we end up with ten different BOR and ten different confirmed BOR functions. This could be as hard to use, maintain, and test as one complex function covering all.

**Comment by rossfarrugia** [comment]
Yes fair point - no hard decisions needed yet on this front. I think for now we need to go with...
- AUG: minor fixes for documentation etc for tester feedback 
- SEP: CRAN release and then start to share specs around new response criteria/indications and make some proposals on next set of enhancements (along with ADTR)
_This of course depends on getting the collaboration agreement finally..._

**Comment by HinalPat** [comment]
As mentioned in our last call, could you check if you are have come across response value of 'NED' - Now evidence of disease? This seems to be appear in BICR data. @irgsandy I wondered if you have since I understand you work a lot with BICR data? I would appreciate feedback so we can assess approach internally.

**Comment by rossfarrugia** [comment]
* **No** evidence of disease :)

**Comment by irgsandy** [comment]
When no target and non-target lesions are identified at baseline, no new lesins are identified on study, the response will be NED. The baseline value is populated as NA, and the TPR is NED. 
In our study, some of the data are reviewed by investigator, and some by BICR. They do not cross check each other.

**Comment by bundfussr** [comment]
Other response values can be handled by `derive_extreme_event()` now (see (Creating ADRS (Including Non-standard Endpoints))[https://pharmaverse.github.io/admiralonco/main/articles/adrs.html] for details).

Thus this issue can be closed.
