### ISSUE TITLE
Checks before testing release

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#52]
Once all the active PRs are merged, then next week we'll need all hands on deck to run through the following and any other checks you can think of:
- website checks for readability / typos / links working etc
- consistency checks across functions documentation 
- NAMESPACE checks for exported functions & check all covered on website reference page

If any others anyone can think of, then please add them here.

If you find anything then add a comment to this issue and we can get them all fixed in one branch. Feel free to do the fix yourself or ask if you need someone else to pick it up.

**Comment by kabis-ops** [comment]
Hi, I had a look at the website and here are some comments on the Reference page: 
- It may be good to align the description for each function as it looks a bit inconsistent 
![image](https://user-images.githubusercontent.com/57490460/175956762-f3654352-307c-4411-a2e4-d64dd844771b.png)
- Should we order the functions like in the workflow?
- Should we remove the empty sections? (ADEVENT, Computations, Source Specifications...)?
- For ADTTE, should we have a link to the admiral functions?
- there is no link to `derive_param_tte()` and `tte_source` (also in all Pre-Defined Time-to-Event Source Objects)

**Comment by rossfarrugia** [comment]
nice spots @kabis-ops - thanks! here's some replies:
1) agree - i'll update in a new branch for this issue
2) i would leave it alphabetical for now and see what we end up doing with admiral core here via https://github.com/pharmaverse/admiral/issues/1105 
3) yes - i already started this via #27 so will finish that one off and ask you to review PR
4) we have links in the ADTTE vignette for this so i think fine not to add more here - let's see how the testers find it then
5) weird - admiral core also has same for `tte_source` at least - will try and fix

**Comment by rossfarrugia** [comment]
Few issues i've spotted:

- i think we need a basic "Get Started" guide as it's not so obvious for a new person picking up our website on how to start - I'll try and add something to this 52_... branch today for this

- @kabis-ops @bundfussr @thomas-neitmann any reason you can see why our devel website doesn't include the ADRS and ADTTE vignettes?

- some of our function documentation pages have inconsistent approaches to the Arguments sections:
  - derive_param_clinbenefit & derive_param_response & filter_pd – doesn’t include any "Permitted Values:"
  - derive_param_bor & derive_param_lasta – gives "Required or Optional:" sections which the others don't
**can anyone pick this one up to fix in this branch please?? or shout if you think this is fine and acceptable**

**Comment by bundfussr** [comment]
@rossfarrugia , regarding the arguments section we do not have a consistent approach which information should be displayed and how it should be displayed. I think we can not solve it before the testing starts.

It seems that we are getting more and more problems with our documentation. I wonder if we should somewhere collect all the issues.

**Comment by bundfussr** [comment]
@rossfarrugia , the vignettes are not displayed because the workflow failed when building the ADRS vignette. I'll investigate.

**Comment by rossfarrugia** [comment]
@bundfussr ok, let's just focus on fixing the vignettes for now then for the testing release and we can come back to the arguments bit later - we can always make new dedicated issues for any such catches that we wont fix just yet, then the testers have transparency anyway as they know this is a working draft that we're releasing

**Comment by kabis-ops** [comment]
@rossfarrugia I can now see the ADRS vignette when i run the pkgdown::site but not the ADTTE vignette. Maybe this is because the pkgdown.yml specifies that this is linked to the keyword 'adtte'  and that we dont have any (we only have tte_source if I am not wrong)? @bundfussr , what do you think?

**Comment by rossfarrugia** [comment]
no worries @kabis-ops - yeh the 52 branch started before the ADTTE got merged to devel so was probably that reason.
