### ISSUE TITLE
Feature Request: Define functions for numeric values of `AVALC`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiralonco#6]
### Feature Idea

Functions should be defined for numeric values of `AVALC`:

- [ ] For "CR", "PR", "SD", "NON-CR/NON-PD", "PD", "NE" values 1 to 6 should be used (for derivation of `AVALN` for response values).
- [ ] For "Y" and "N" values 1 and 0 respectively should be used (for derivation of `AVALN` for binary response values).
- [ ] For  'PD', 'NE', 'NON-CR/NON-PD', 'SD', 'PR', 'CR' values 1 to 6 should be used (for selecting worst response if there is more than one per date).

If implemented the class from https://github.com/pharmaverse/admiral/issues/1021, should be used.

### Relevant Input

What should the input look like? REMINDER: no patient level data or company sensitive information should be shared via this open public issue

### Relevant Output

What should the output look like? REMINDER: no patient level data or company sensitive information should be shared via this open public issue

### Reproducible Example/Pseudo Code

We love example code and it will speed up the process! REMINDER: no patient level data or company sensitive information should be shared via this open public issue

**Comment by rossfarrugia** [comment]
@bundfussr do you see this as still needed with the ADRS workflow? let me know and i can add it in if so. i think the worst order at least is probably no longer needed here.

**Comment by bundfussr** [comment]
I am not sure. It could be helpful to ensure that the derivation of `AVAL` is consistent.

Worst order is not used in admiralonco. Should we move it to admiralroche?

The second one is not onco specific. Should we move it to admiral core?

**Comment by rossfarrugia** [comment]
@bundfussr in hindsight we probably cant make a decision on this until we get a decision from the core leads on whether we'll implement get_map() or just let the user define their own function using case_when(). let me know the resolution of that one from the Q&A meets you have at core team and then we could make a call on this one. whichever way i'm not really seeing anything needed for admiralonco here as we dont use AVAL in any of the derivation functions, and in our Step1 of ADRS workflow we're clear such pieces are done by the user as pre-processing.

**Comment by rossfarrugia** [comment]
ON HOLD for now as explained above - not needed for foundational release of {admiralonco}

**Comment by bundfussr** [comment]
Not needed anymore.
