### ISSUE TITLE
Feature Request: Define `source()` objects for confirmed response and confirmed best overall response

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiralonco#7]
### Feature Idea

Define `source()` objects for confirmed response and confirmed best overall response. The objects should be used as input for `admiral::derive_param_joined_multi()` (see https://github.com/pharmaverse/admiral/issues/1031).

### Relevant Input

What should the input look like? REMINDER: no patient level data or company sensitive information should be shared via this open public issue

### Relevant Output

What should the output look like? REMINDER: no patient level data or company sensitive information should be shared via this open public issue

### Reproducible Example/Pseudo Code

We love example code and it will speed up the process! REMINDER: no patient level data or company sensitive information should be shared via this open public issue

**Comment by rossfarrugia** [comment]
will close in favour of new ADRS workflow - issues to be added
