### ISSUE TITLE
Feature Request:  ADRS derive_param_confirmed_resp change needed for same date across multiple visits

### ISSUE THREAD

**Issue by oreillb1** [pharmaverse/admiralonco#78]
### Feature Idea

derive_param_confirmed_resp requires an update to process same date having multiple visits in RS domain. This can happen due to study design when the date of  [RS.VISIT] = 'Tumor Assessment Week'  is the same date for e.g. [RS.VISIT] = 'Treatment Discontinuation' or an unscheduled visit. Processing of multiple parameters is affected e.g. ADRS.PARAMCD] = 'CRSP'. Changes input values max_nr_ne or accept_sd made no difference.

**Outcome:**
Discussed with Barbara and Stefan over emails and we will update documentation here to make clearer our admiralonco expectations around duplicate visits:

For functions, we should add to the description of the input datasets that we expect that STUDYID, USUBJID, and ADT are a unique key.

For ADRS vignette, we should include more detail in the preprocessing of input records section around expectations for uinque key and no duplicate records via ANL01FL.

**Comment by bundfussr** [comment]
Thanks for creating this issue.

How does RS.VISIT affect the derivation of CRSP? Could you provide your specs for the CRSP parameter?

**Comment by oreillb1** [comment]
More information to follow but I used derive_param_confirmed_resp code from the reference section as the starting point. In our  study data we currently follow in-house ADaM specs for ADRS and ADTTE parameters.

**Comment by bundfussr** [comment]
@oreillb1 , if you are using the Roche standard specs, you should use `filter_source = PARAMCD == "OVR" & ANL01FL == "Y"`. `ANL01FL == "Y"` ensures that there is only one observation per subject and date selected.

**Comment by oreillb1** [comment]
Recommended change was tried but did not solve the issue.  Same [RS.RSDTC] can be used for different [RS.VISIT] and the data entries are valid.

**Comment by oreillb1** [comment]
Seeing duplicated record warnings when most parameters are created and data entries are valid. 
Dataset contains duplicate records with respect to `STUDYID`, `USUBJID` and `ADT`

**Comment by bundfussr** [comment]
If you have the same RSDTC for different RS.VISIT, ANL01FL should flag one of them (at least if you are using the Roche standard specs).

**Comment by rossfarrugia** [comment]
Discussed with Barbara and Stefan over emails and we will update documentation here to make clearer our admiralonco expectations around duplicate visits: 

For functions, we should add to the description of the input datasets that we expect that STUDYID, USUBJID, and ADT are a unique key. 

For ADRS vignette, we should include more detail in the preprocessing of input records section around expectations for uinque key and no duplicate records via ANL01FL.

**Comment by rossfarrugia** [comment]
@bundfussr hope you're ok to pick this one up when back and i can review? i think you'll know best where to place this extra documentation.
