### ISSUE TITLE
Feature Request:  ADRS vignette, change to derive_var_obs_number

### ISSUE THREAD

**Issue by oreillb1** [pharmaverse/admiralonco#79]
### Feature Idea

ASEQ is not created in output ADRS whenever duplicates are found. Duplicates occur when [RS.VISIT] and [RS.RSDTC] are identical and it is a commonly seen site data entry issue that is usually fixed at some point. 
Addition to vars statement is required, suggestion is to include RSSEQ or RSSPID.
# Derive analysis sequence
adrs <- adrs %>%
  derive_var_obs_number(
    by_vars = vars(STUDYID, USUBJID),
     order = vars(PARAMCD, ADT, VISITNUM, RSSEQ),
    check_type = "error"
  )

**Comment by bundfussr** [comment]
@oreillb1 , thanks for creating the issue. The suggested change definitely makes sense.

Would you like to implement it?

**Comment by oreillb1** [comment]
Yes please go ahead to implement this change.

**Comment by rossfarrugia** [comment]
@oreillb1 Stefan was offering whether you'd like us to grant you write access to this repo to be able to make the fix yourself? If you'd like to try a contribution that is. no pressure though, and i'm happy to make this update if you prefer. thanks for spotting and raising it!

**Comment by rossfarrugia** [comment]
@yangc71 i saw a branch exists for this one now but reminder to use the "@devel" suffix naming - rename this before making the PR. thanks for the contributions!

**Comment by rossfarrugia** [comment]
@oreillb1 the issue is already closed thanks - Annie fixed it.
