### ISSUE TITLE
Feature Request:  Define `source()` objects for best overall response

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/admiralonco#8]
### Feature Idea

Define `source()` objects for best overall response. The objects should be used as input for `admiral::derive_param_merged_multi()` (see https://github.com/pharmaverse/admiral/issues/1030).

### Reproducible Example/Pseudo Code

```
bor_cr <- source(
  filter_add = AVALC == "CR",
  new_vars = vars(AVALC, ADT))
```

**Comment by rossfarrugia** [comment]
will close in favour of new ADRS workflow - issues to be added
