### ISSUE TITLE
Check around consistency of derivation function arguments

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#80]
Examples include `source_pd` being optional in some and required in others. Plus how the assertions are done. _To be expected with many different individuals programming these._

@sgorm123 to look across and make a proposal of how to better align these.

Updated to discussion and created 3 seperate issues to resolve these points:
https://github.com/pharmaverse/admiralonco/issues/128
https://github.com/pharmaverse/admiralonco/issues/129
https://github.com/pharmaverse/admiralonco/issues/130

**Comment by sgorm123** [comment]
Tasks to perform after initial review:

1. Need confirmation of consistency in headers regarding: REQUIRED or OPTIONAL PARAMS, DEFAULT VALUES, PERMITTED VALUES (i.e. for all arguments, only those relevant or none at all) from ADMIRAL team. @rossfarrugia to confirm. After which I can make the relevant updates.
2. @rossfarrugia to confirm if we are to use `inheritParams` to aid with maintenance and consistency. This will be easy to implement, but it does cause a bit of an issue to navigate code for the user.  If we do not use this, then I shall manually update the @param descriptions across functions (if the argument is the same).
3. Remove assertions in derive functions that are repeated in filter_pd.
4. Update the call to filter_pd in all derive_param functions, to make it optional.
5. Could consider a utility for the assertions as the are the same in many of the functions, @rossfarrugia to confirm.
6. Update order of arguments so they are the same across functions.

**Comment by rossfarrugia** [comment]
@sgorm123 summary of core dev team discussions today to your above points:

1. @thomas-neitmann will add draft guidance as a comment to https://github.com/pharmaverse/admiral/issues/1295 and will tag you so you have something to work from. we might evolve it over time.

2. everyone was happy for you to experiment with `inheritParams` as you suggested to see how we could better maintain consistency of documentation across functions, and then make a PR and we could get few devs to review and see what they think. they all recognised the issue as a common challenge across our packages, but wondered in practice if hiding away these in a central file might make it more difficult for developers who want to quickly delve into and understand one function code. i think seeing something via admiralonco as a guinea pig would help us to get a better feel on whether this is the way to go for admiral too.

5. everyone felt this idea was a bit against the modular ideology of 1 function for 1 purpose of admiral, and building in an extra layer may make it more complex for devs and they may become less likely to really question whether each assertion is appropriate and whether any should be added. so although it involves a bit of copy and paste and alignment effort, everyone preferred the transparent approach of just including these directly at the start of each function.

Let me know if any follow-up comments you want me to take back, but hope all makes sense.

**Comment by rossfarrugia** [comment]
@sgorm123 you've probably seen already but there are some interesting inherit variations that might be worth exploring too: https://r-pkgs.org/man.html#inheriting-documentation

**Comment by rossfarrugia** [comment]
@sgorm123 will close this one as its no longer relevant now we have the 3 split issues above
