### ISSUE TITLE
Documentation:  extra ADRS vignette example

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#81]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

 from GSK tester feedback: add an example to the ADRS vignette for where PD date is sourced from ADSL instead of ADRS

**Comment by bundfussr** [comment]
I think we should also add an example where an analysis flag (`ANLzzFL`) is added flagging the observations before PD (for the OVR parameter). I would consider this as the best option from CDISC, reviewer, and programmer perspective.

**Comment by rossfarrugia** [comment]
Also include example cases for NACT
