### ISSUE TITLE
Documentation:  derive_param_clinbenefit - clarify response values considered

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#85]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

The documentation says "(i.e., responses exclusive of `NA`, `NE`, `ND`, and `PD`)". Some companies may also want to exclude other response values like "NON-CR/NON-PD" for example here as not being eligible for clinical benefit. Add a note to the documentation that the user can exclude any additional response values using the `filter_source` argument and include an extra example for this.

Also add more details in 'details' section that response is considered directly as CBR based on `source_resp` argument. For example in most cases this would be `PR` or `CR` but the user has complete control of what gets considered as a response, as they feed in the date for any responder here.

**Comment by bundfussr** [comment]
I would prefer adding an argument for the values to be considered as eligible for clinical benefit. I think this makes the function easier to understand and use.

**Comment by rossfarrugia** [comment]
@sgorm123 @amitjaingsk any thoughts on Stefan's proposal above? As we ran out of time to discuss this yesterday. I'm OK with it personally as it gives the users more control and then we can be a bit more prescriptive in the documentation, as requested by Amit.

**Comment by amitjaingsk** [comment]
@rossfarrugia @bundfussr I like the idea, to add a parameter where we can pass the values. Just to understand though, as per the definition of clinical benefit, we basically have 2 part checks 1. confirmed/unconfirmed BOR value of CR,PR. 2. Using overall response ( certain responses) records with min. day condition. Are we planning to send the general list of CR,PR,SD etc.. or for individual the conditions of CBR above?

**Comment by rossfarrugia** [comment]
@amitjaingsk as i understand it check part 1 would get covered by `source_resp` still, so the user just needs to pass in to the new argument whichever response values should be considered eligible for part 2, and i'd say default would be `SD` and `NON-CR/NON-PD`. agree @bundfussr?

**Comment by rossfarrugia** [comment]
actually probably best to just add `PR` and `CR` too to that default list as it protects against the user providing something crazy to `source_resp` which for some reason didn't already pick up a PR/CR patient as a responder.

**Comment by bundfussr** [comment]
Yes, I would add PR and CR to the default, too. These values should be considered when confirmed response is specified for `source_resp`.
