### ISSUE TITLE
Make derive_param_response() consistent with derive_param_bor() - AVALC->AVAL

### ISSUE THREAD

**Issue by jj1994** [pharmaverse/admiralonco#88]
The AVAL values are hard-coded in derive_param_response() only. Maybe we should change it and add the aval_fun argument to be consistent.

Also: for this function and derive_param_bor()/derive_param_confirmed_bor() I don't find anything to explicitly states that internally to find the BOR, we have used these mapping . I think we should clarify in documentation that this function is only for mapping AVALC TO AVAL but internal processing is done on default values.

**Comment by rossfarrugia** [comment]
Pavan will take this issue on once he gets github access

**Comment by rossfarrugia** [comment]
@pk505289 can you let us know if this PR will be available early this week as our target is to:
- have the release PRs reviewed and merged by this Wednesday
- then we can try and make a release for our first CRAN submission to be ready for offical release hopefully by 12th

Tagging @amitjaingsk to also chase up please.

**Comment by sgorm123** [comment]
@rossfarrugia do you want me to add this, seeing as I am also updating the tests?

I presume it is just a case of acccepting an aval_fun() function, similar to _bor and _confirmed_bor, correct?

#' @param aval_fun Function to map character analysis value (`AVALC`) to numeric
#'                 analysis value (`AVAL`)
#'
#'   The (first) argument of the function must expect a character vector and the
#'   function must return a numeric vector.
#'

**Comment by bundfussr** [comment]
@sgorm123 , I have implemented a utility function for calling `aval_fun()`. See https://github.com/pharmaverse/admiralonco/pull/147. It should be used in `derive_param_response()`, too.

**Comment by sgorm123** [comment]
ah great, I can make this change once it is confirmed I should make the update.  I dont want to get in the way of @pk505289  on this one. 

@pk505289, please note that I have updated the tests for this function via this PR: https://github.com/pharmaverse/admiralonco/pull/145

**Comment by pk505289** [comment]
Ok.. Ill take a look and make the necessary changes

**Comment by pk505289** [comment]
I have added a piece of code.. can you please take a look

**Comment by rossfarrugia** [comment]
@pk505289 please make a PR as per usual admiral process and we can review.

@bundfussr can you check the question from @sgorm123 about dataset_adsl and reply please? sorry struggling to keep up with all the messages i'm getting tagged in across different admiral packages this week.

**Comment by bundfussr** [comment]
@sgorm123 , I think we clarified the question regarding `dataset_adsl` in https://github.com/pharmaverse/admiralonco/pull/145 or do you have still concerns?

**Comment by sgorm123** [comment]
yes, all good on dataset_adsl, my fault for not adding a column to the test adrs dataframe.

**Comment by sgorm123** [comment]
@pk505289 I dont see any changes in the feature bracnh for this: https://github.com/pharmaverse/admiralonco/blob/88_avalc2aval/R/derive_param_response.R

where have you made the change? Remember to also pull all the changes from the devel branch, as there are many.
