### ISSUE TITLE
Documentation:  make function argument sections consistent

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralonco#90]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

tester feedback:

Comparing for example https://pharmaverse.github.io/admiralonco/test/reference/derive_param_bor.html#arguments with https://pharmaverse.github.io/admiralonco/test/reference/derive_param_confirmed_bor.html#arguments we got the feedback:
the "Arguments" documentation is not same across all functions: for eg "derive_param_bor" had provided if the parameter is required or not. but if we look into consistency across all references to provide permistted values, optional or not, defualt values.

also see https://github.com/pharmaverse/admiraldev/issues/72 from admiral.

we should include the useful PERMITTED VALUES and DEFAULT VALUES sections in all functions. around REQUIRED/OPTIONAL part this is still being discussed at admiral dev team and i will add here the decision.

**Comment by rossfarrugia** [comment]
Waiting for decision from admiral core team on the issue mentioned above - and a programming strategy update.

**Comment by bundfussr** [comment]
The admiralonco functions are superseded by derive_extreme_event(). I would not expect that we develop them further. Thus I am closing this issue.
