### ISSUE TITLE
Documentation and assertion checking in derive_param_bor

### ISSUE THREAD

**Issue by sgorm123** [pharmaverse/admiralonco#91]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

Update documentation around ADSL subjects being added and also the minimum day requirement for best response. 
Also, update assertion for subject_keys so it errors at the appropriate time.

See issues log for more details: https://exbpbox.ent.box.com/file/984133774075

**Comment by sgorm123** [comment]
Plus additional information in dataset_adsl param

#' @param dataset_adsl ADSL input dataset.
#'
#'   The variables specified for `subject_keys`is expected. For each subject of
#'   the specified dataset a new observation is added to the input dataset. Variables
#'   in `dataset_adsl` that also appear in `dataset` will be populated with the
#'   appropriate subject-specific value for these new observations.

**Comment by sgorm123** [comment]
@rossfarrugia This has been updated as part of PR 145 https://github.com/pharmaverse/admiralonco/pull/145, see the differences in derive_param_bor.

**Comment by rossfarrugia** [comment]
Thanks @sgorm123 - we usually close these once we make the release. most get auto-closed through our PR naming convention.
