### ISSUE TITLE
BOR Unconfirmed and Confirmed: Add Reasons for ‘Not Evaluable’ (NE)

### ISSUE THREAD

**Issue by NeetuSa** [pharmaverse/admiralonco#92]
### Feature Idea

For subjects with BOR as NE, it is recommended to add details on the reason for Not Evaluable in the variable AVALC.

- No adequate baseline assessment 
- No evidence of disease at baseline
- No post-baseline assessments due to early death
- Post-baseline assessments due to other reasons
- All post-baseline assessments have overall response of NE 
- New anti-cancer therapy started before first post-baseline 
- SD too early 
- PD too late

**Comment by rossfarrugia** [comment]
@NeetuSa we discussed at the core dev team and we found that this was a reporting need not seen at our companies and so for now we've decided not to implement in admiralonco, as we felt it would add extra complexity for users and also we thought such pieces would be difficult to generalise to achieve at an industry level.
