### ISSUE TITLE
Bug: BOR Unconfirmed and Confirmed-> Add Reference window for Progressive Disease (PD)

### ISSUE THREAD

**Issue by NeetuSa** [pharmaverse/admiralonco#93]
### What happened?

Example, Scenario: The study data has Not Evaluable as BOR whereas admiral code has PD as BOR . 
The reason for this mismatch is: The study has Not Evaluable as BOR because all the PD occurred after XX days for those subjects, in admiral, there is no reference window for PD so it is considering PD as BOR.

**Comment by rossfarrugia** [comment]
@NeetuSa the way we do this for admiral is that only `SD` or `NON-CR/NON-PD` need to consider the `where ADT >= reference_date + ref_start_window` clause. The reason being any response or PD should always be counted for BOR as it doesn't matter how quickly after baseline that the tumor growth or shrinkage occurs in this case, as it is clearly an event of interest. Whereas something like SD may need a "protocol specified minimum time from baseline" (from RECIST 1.1 guidelines) as if a patient got assessed a couple of days after baseline then chances are there would be no significant change in tumor size, but assuming that as a BOR=SD could be misleading, as there hasn't been time yet for any treatment effect.

@bundfussr @sgorm123 @amitjaingsk please share any further views, but personally I'm happy the admiral current approach here is sufficient and matches the rationale of the RECIST 1.1 guidelines.

**Comment by PranavSoan** [comment]
@rossfarrugia  
This is a special and rare case and is referred as "PD too late" (which is similar to the consideration for "SD too early"), here the patients with "NE" BOR will be summarized when the first documented PD is recorded more than Z weeks after 'start date' with no qualifying response in between and a late PD may be classified as ‘SD of insufficient duration’

**Comment by rossfarrugia** [comment]
Thanks for the explanation @PranavSoan! I didn't find mention of this in RECIST 1.1 guidelines - do you have any public literature you could share detailing this approach? 

We don't usually cater for such rare cases in admiral as per our scope https://pharmaverse.github.io/admiral/index.html#scope, as otherwise our functions, documentation and testing becomes endlessly complex and we would lose our design principles: https://pharmaverse.github.io/admiral/index.html#admiral-manifesto.

**Comment by rossfarrugia** [comment]
@NeetuSa @PranavSoan we discussed at the core dev team and we found that this was a reporting need not seen at our companies and so for now we've decided not to implement in admiralonco, as we felt it would add extra complexity for users (see the links shared above which detail the principles we try to apply to decision making in admiral). The requirement could be achieved with some company specific processing in addition to using our admiralonco functions.
