### ISSUE TITLE
Bug: BOR Unconfirmed and Confirmed->Doesn’t handle New-Anti Cancer Therapy (NAT)

### ISSUE THREAD

**Issue by NeetuSa** [pharmaverse/admiralonco#94]
### What happened?

Example, Scenario: The study data has Not Evaluable-NAT as BOR whereas admiral has PD or SD as BOR. 
The reason for this mismatch is: The study has Not Evaluable-NAT as BOR because the study ignores all the assessments after NAT date, admiral does not handle NAT scenario, so it is considering SD or PD as BOR which is happening post NAT date.

**Comment by rossfarrugia** [comment]
thanks @NeetuSa - we also heard others struggling with how to approach this so we definitely need to add more details. NACT/NAT is covered at https://pharmaverse.github.io/admiralonco/test/articles/adrs.html#input, but we will add more ADRS/ADTTE examples to show how this can be dealt with by users in the pre-processing steps. There are open issues for these so I will close this one and the updates will be made there in the vignettes.
