### ISSUE TITLE
Bug: BOR Unconfirmed and Confirmed->Doesn't handle No evidence/disease at baseline.

### ISSUE THREAD

**Issue by NeetuSa** [pharmaverse/admiralonco#95]
### What happened?

Add a reference window for screening to handle No evidence/disease at baseline.

**Comment by PranavSoan** [comment]
@rossfarrugia  
In general, all studies on solid tumors enroll patients with measurable disease (reporting at least 1 target lesion at baseline with a diameter size). Below are some of the scenarios where patients who have no disease at baseline are included in the trial - 
1. Some studies on prostate cancer or breast cancer allows enrollment of patients that have non-measurable disease at baseline (i.e. the patients have diffuse lesions in bone that cannot be measured). These patients are categorized as patients with non-measurable disease at baseline.
2. Some studies use BICR data. In this case, BICR review scans at baseline and may report that they cannot find disease at all (measurable or non-measurable) in a patient scan(s) at baseline. These patients are categorized as patients with non-measurable disease at baseline per Investigator.

**Comment by rossfarrugia** [comment]
Thanks @PranavSoan - this is useful! And is the expectation here for BOR that such patients just get an ADRS record with BOR categorised as "No evidence/disease at baseline"? Given there's nothing to compare the post-baseline tumor assessments back to, to see if any response.

**Comment by PranavSoan** [comment]
@rossfarrugia Yes, we can have the ADRS record, and for these patients the BOR, can be "NOT EVALUABLE - NO EVIDENCE OF DISEASE AT BASELINE"

**Comment by rossfarrugia** [comment]
See response at https://github.com/pharmaverse/admiralonco/issues/92. The admiralonco functions could be used to get out a BOR as NE (e.g. see `missing_as_ne` argument) and then company-specific post-processing could be added to further decorate this response value with more details.
