### ISSUE TITLE
Feature Request: Progression Free Survival->Add parameters on censor conditions argument to capture the censoring for subjects without PD/Death event

### ISSUE THREAD

**Issue by NeetuSa** [pharmaverse/admiralonco#96]
### Feature Idea

Example, Scenario: When subject is given New Anti-Cancer Therapy (NAT), the study needs to consider censoring at the last Radiological Assessment date.

**Comment by rossfarrugia** [comment]
Will close this issue and will address the update as part of issue 86 as we had similar feedback request from GSK. thanks @NeetuSa!
